name: Scrape covid19 risk area
on:
  schedule:
    - cron: '30 4,10,14 * * *' 
   #- cron: '30 12,18,22 * * *'  # CST
    # UTC time vs CST Asia/Shanghai time
    # see https://www.worldtimeserver.com/time-zones/utc-to-cst/
  push:
    branches: main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# see [twitter](https://twitter.com/RCoderWeb/status/1495142643726225413)
# see [blog](https://sabeeh.medium.com/using-github-actions-as-a-job-scheduler-for-r-scripts-7b92539372f4)

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "generate-data"
  generate-data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest #macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install cURL Headers
        run:  |
          sudo apt-get update
          sudo apt install -y libcurl4-openssl-dev
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          
      - name: Setup renv
        run: |
          install.packages('renv')
        shell: Rscript {0}
        
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/renv #~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install dependencies
        run: |
          renv::restore()
        shell: Rscript {0}
  
      - uses: browser-actions/setup-firefox@latest
      - run: firefox --version
      
      - name: Scrape the data
        run: |
          source("scrape-covid19-xrh.R", encoding='UTF-8')
        shell: Rscript {0}
      
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New Executive Order signed - data updated!' || echo "No changes to commit"
          git push
