on:
  schedule:
    - cron: '30 7 * * *'

name: Scrape covid19 risk area

jobs:
  bot-post:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: browser-actions/setup-firefox@latest 
      - run: firefox --version 
      - name: Install RSelenium  and dependencies
        run: Rscript -e 'install.packages(c("tidyverse","RSelenium","dplyr","lubridate"))'
      - name: Scrape the data
        run: Rscript scrape-covid19.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New Executive Order signed - data updated!' || echo "No changes to commit"
          git push